In [3]:
import numpy as np 

# Basic

In [21]:
arr = np.array([1, 2, 3, 4, 5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[0]

1

In [24]:
arr[-1]

5

In [26]:
arr[0:3]

array([1, 2, 3])

In [27]:
# we also create multidimensional array using numpy

In [37]:
arr = np.array([[[1,2,3], [4,6,7], [8,9,0]], [[1, 2, 3], [3, 4, 5], [5, 6, 7]]])

In [38]:
arr

array([[[1, 2, 3],
        [4, 6, 7],
        [8, 9, 0]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]])

In [41]:
# attributes 

# shape
print(arr.shape)

# Dimensional
print(arr.ndim)

# size of the array
print(arr.size)

# datatypes of the array
print(arr.dtype)

(2, 3, 3)
3
18
int32


In [50]:
# storing the string data inside the array
arr = np.array([
    [1, 2, 3],
    [2, 3, "hello"],
    [4, 5, 3], 
])

In [49]:
arr

array([['1', '2', '3'],
       ['2', '3', 'hello'],
       ['4', '5', '3'],
       ['3', '5', '6']], dtype='<U11')

In [51]:
# The dtype='<U11' refers to the data type used in NumPy (or other similar libraries) for storing string data,

In [52]:
# we have text data inside the array that time we cannot change the typecasting
arr = np.array([
    [1, 2, 3],
    [2, 3, "hello"],
    [4, 5, 3], 
], dtype="int64")

ValueError: invalid literal for int() with base 10: 'hello'

In [54]:
# we have number in string type inside the array we can typecasting 
arr = np.array([
    [1, 2, 3],
    [2, 3, "5"],
    [4, 5, 3], 
], dtype="int64")

arr.dtype

dtype('int64')

In [58]:
arr = np.array([
    [1, 2, 3],
    [2, 3, "hello"],
    [4, 5, 3], 
])

arr.dtype

dtype('<U11')

In [59]:
type(arr[0][1])

numpy.str_

In [66]:
d= {'1':'A'}

arr = np.array([
    [1, 2, 3],
    [2, 3, d],
    [4, 5, 3], 
])

arr.dtype

dtype('O')

In [64]:
type(arr[1][0])

int

In [67]:
d= {'1':'A'}

arr = np.array([
    [1, 2, 3],
    [2, 3, d],
    [4, 5, 3], 
], dtype="int64")

TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

# Filling array 

In [68]:
fullArray = np.full((2, 4, 3), 5)

In [69]:
fullArray

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [70]:
# fill zero using the zero method 
zeroArray = np.zeros((2, 4, 3))

In [71]:
zeroArray

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
# Fill ones using the ones method 

onesArray = np.ones((2, 4, 3))

In [73]:
onesArray

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
# The np.empty() method in NumPy creates an uninitialized array with a specified shape and data type, 
# where the values are left as random garbage from memory.

In [76]:
emptyArray = np.empty((2, 3, 4))

In [77]:
emptyArray

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [78]:
# arange simplar to python range 
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [83]:
# linspace 
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
"""np.arange(): Generates an array with evenly spaced values within a specified range, based on a start, 
\stop, and step size.
    
np.linspace(): Creates an array with a specified number of evenly spaced values between a start and 
stop value, inclusive."""

# arange -> evenly spaced between the range 
# linspace -> evenly spaced between the given value 

### NAN 

In [ ]:
"""
NaN (Not a Number): Represents undefined or unrepresentable numerical results, 
such as the result of 0/0 or infinity - infinity.

Inf (Infinity): Represents a value that exceeds the range of finite numbers,
such as the result of division by zero (excluding 0/0).
"""

In [85]:
np.nan

nan

In [86]:
np.nan + 5

nan

In [89]:
np.inf 

inf

In [90]:
np.inf - np.inf

nan

# Mathematical operations 

In [92]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]

a1 = np.array(l1)
a2 = np.array(l2)

In [93]:
l1 + 2

TypeError: can only concatenate list (not "int") to list

In [94]:
a1 + 2

array([3, 4, 5, 6, 7])

In [95]:
# we do not perform the mathematical operations in python list do only np array 

In [96]:
l1 * 2 # repeat or extant the list 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [97]:
a2 * 2 # it is map the value 

array([12, 14, 16, 18,  0])

In [98]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1], [2]])

a1

array([1, 2, 3])

In [99]:
a2

array([[1],
       [2]])

In [101]:
a1 + a2

array([[2, 3, 4],
       [3, 4, 5]])

In [102]:
a1 = np.array([
    [1, 2, 3], 
    [2, 3, 4]
])

np.sqrt(a1) # tan, cos, log10, log etc  

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ]])

# Array method 

In [103]:
a1 = np.array([1, 2, 3])

In [104]:
a1

array([1, 2, 3])

In [ ]:
# append

In [106]:
np.append(a1, [6, 7, 8])

array([1, 2, 3, 6, 7, 8])

In [ ]:
# insert 

In [110]:
np.insert(a1, 3, [8, 9, 0])

array([1, 2, 3, 8, 9, 0])

In [111]:
a2 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

In [112]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Delete 

In [113]:
np.delete(a2, 1)

array([1, 3, 4, 5, 6])

In [114]:
np.delete(a2, 1, 0) # zero means row 

array([[1, 2, 3]])

In [115]:
np.delete(a2, 1, 1) # one means column

array([[1, 3],
       [4, 6]])

# structure Method 

In [128]:
a = np.array([np.arange(1, 6), np.arange(6, 11), np.arange(11, 16), np.arange(16, 21)])

In [129]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [130]:
a.shape

(4, 5)

In [131]:
a.reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [132]:
a.reshape(20,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [133]:
a.reshape(2, 10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [134]:
a.reshape(5, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [135]:
a.resize((10, 2))

In [136]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [137]:
a = np.array([np.arange(1, 6), np.arange(6, 11), np.arange(11, 16), np.arange(16, 21)])

In [138]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [139]:
# Flatten 
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [140]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [141]:
# ravel 
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [142]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
"""
flatten(): Returns a copy of the array as a 1D array.
ravel(): Returns a flattened 1D array, but if possible, it returns a view of the original array (no copy).
"""

In [ ]:
# Difference of flatten and ravel 

In [143]:
var1 = a.flatten()
var1[2] = 100
var1

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [144]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [145]:
var1 = a.ravel()
var1[2] = 100
var1

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [146]:
a

array([[  1,   2, 100,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [147]:
a = np.array([np.arange(1, 6), np.arange(6, 11), np.arange(11, 16), np.arange(16, 21)])

In [148]:
# Flat 
[i for i in a.flat]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [150]:
# Transpose 

In [151]:
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [154]:
a.swapaxes(0, 1)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

# Concatenating, Stacking, Splitting

In [163]:
a1 = np.array([np.arange(0, 5), np.arange(5, 10)])
a2 = np.array([np.arange(11, 16), np.arange(16, 21)])

In [164]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [165]:
a2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [168]:
np.concatenate((a1, a2), axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [169]:
np.concatenate((a1, a2), axis = 1)

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [171]:
np.stack((a1, a2))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [172]:
np.vstack((a1, a2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [173]:
np.hstack((a1, a2))

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [174]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [176]:
np.split(a1, 2, axis=0)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [178]:
np.split(a1, 2.5, axis=1) # equaly division the array 

[array([[0, 1, 2],
        [5, 6, 7]]),
 array([[3, 4],
        [8, 9]])]

# Aggregate Functions 

In [179]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [180]:
a1.min()

0

In [181]:
a1.max()

9

In [182]:
a1.mean()

4.5

In [183]:
a.std()

5.766281297335398

In [184]:
a.sum()

210

In [185]:
np.median(a)

10.5

# Random 

In [186]:
np.random.randint(100)

70

In [187]:
np.random.randint(100, size=(2, 3, 4))

array([[[45, 66, 19, 55],
        [68, 45,  4, 94],
        [33, 11, 54, 20]],

       [[83, 20, 18, 91],
        [38, 31, 46, 51],
        [58, 62,  1,  1]]])

In [188]:
np.random.randint(90, 100, size=(2, 3, 4))

array([[[98, 99, 94, 93],
        [92, 95, 98, 91],
        [98, 93, 91, 90]],

       [[99, 94, 96, 92],
        [96, 98, 97, 96],
        [95, 99, 92, 99]]])

In [191]:
np.random.binomial(20, p=0.5, size=(5, 10)) # p is probability size

array([[ 6, 10, 12, 11, 11,  7,  5, 13, 10, 14],
       [10, 11,  4,  9,  6, 12,  7,  8, 12, 13],
       [11, 12,  9, 11, 11, 10, 12, 12, 14,  9],
       [ 6, 11, 12,  8, 11,  9, 10, 11, 13, 11],
       [12, 11, 11, 14, 13,  6, 10, 11, 10, 14]])

In [192]:
np.random.normal(loc = 170, scale = 15, size = (5, 10)) # loc -> mean 

array([[185.05434813, 184.62817098, 161.99176231, 178.03673255,
        173.92576722, 180.55571201, 167.95457476, 172.4983043 ,
        141.26505757, 152.83524707],
       [163.85997211, 173.31899757, 171.46040387, 153.31514252,
        155.72549227, 152.09821595, 162.18217684, 162.8973292 ,
        176.41739739, 165.96547143],
       [178.82809106, 173.39586704, 177.94005712, 144.69919024,
        155.78654029, 208.54491226, 140.05874317, 172.95482791,
        175.07573661, 153.69075204],
       [183.29495753, 199.05221589, 204.38714027, 131.17668538,
        175.38363381, 151.07852099, 158.75250608, 138.08238635,
        137.27264276, 160.50614184],
       [185.11788694, 174.83273101, 153.10213851, 170.31209947,
        184.1129905 , 156.92789885, 198.70285172, 170.4776436 ,
        151.15775269, 171.72324237]])

In [194]:
np.random.choice([2, 3, 4, 5, 40], size=(5, 3))

array([[40,  4,  5],
       [ 4, 40, 40],
       [ 5,  2,  3],
       [40,  5,  4],
       [ 4,  4, 40]])

# Exporting & Importing 

In [195]:
np.save("myArray.npy", a)

In [196]:
np.load("myArray.npy")

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [197]:
np.savetxt("myArray.csv", a, delimiter=",")

In [200]:
np.loadtxt("myArray.csv", delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])